import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './components/Header/header'
import './styles/style.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Macaron Shop',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<body className={inter.className}>
				<Header />
				{children}
			</body>
		</html>
	)
}
