"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = RootLayout;
exports.metadata = void 0;
var _google = require("next/font/google");
var _header = _interopRequireDefault(require("./components/Header/header"));
require("./styles/style.css");
function _interopRequireDefault(obj) {
  return obj && obj.__esModule ? obj : {
    default: obj
  };
}
var inter = (0, _google.Inter)({
  subsets: ['latin']
});
var metadata = exports.metadata = {
  title: 'Macaron Shop',
  description: 'Generated by create next app'
};
function RootLayout(_ref) {
  var children = _ref.children;
  return /*#__PURE__*/React.createElement("html", {
    lang: "en"
  }, /*#__PURE__*/React.createElement("body", {
    className: inter.className
  }, /*#__PURE__*/React.createElement(_header.default, null), children));
}